---
##############################
# FRONTEND - Amazon Linux
##############################

- name: Configure Frontend
  hosts: frontend
  become: yes

  tasks:

    - name: Disable SELinux permanently
      replace:
        path: /etc/selinux/config
        regexp: '^SELINUX=.*'
        replace: 'SELINUX=disabled'
      ignore_errors: yes

    - name: Disable SELinux immediately
      command: setenforce 0
      ignore_errors: yes

    - name: Stop firewalld if running
      service:
        name: firewalld
        state: stopped
        enabled: no
      ignore_errors: yes

    - name: Install Nginx
      yum:
        name: nginx
        state: present

    - name: Start and Enable Nginx
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Configure Reverse Proxy to Backend
      copy:
        dest: /etc/nginx/conf.d/reverse.conf
        content: |
          server {
              listen 80;
              location / {
                  proxy_pass http://{{ hostvars['u21.local']['ansible_host'] }}:19999;
              }
          }

    - name: Restart Nginx
      service:
        name: nginx
        state: restarted


##############################
# BACKEND - Ubuntu
##############################

- name: Configure Backend
  hosts: backend
  become: yes

  tasks:

    - name: Stop firewalld if exists
      service:
        name: firewalld
        state: stopped
        enabled: no
      ignore_errors: yes

    - name: Install Netdata
      shell: |
        bash <(curl -Ss https://my-netdata.io/kickstart.sh) --dont-wait

    - name: Ensure Netdata is running
      service:
        name: netdata
        state: started
        enabled: yes
      ignore_errors: yes
